name:    ted2srt
version: "2.20180426"

dependencies:

# Due to a bug in GHC 8.0.1, we block its usage
# See: https://ghc.haskell.org/trac/ghc/ticket/12130
- base >=4.8.2.0 && <4.9 || >=4.9.1.0 && <5

- aeson
- beam-core
- beam-postgres
- bytestring
- conduit < 1.3
- conduit-extra < 1.3
- containers
- directory
- either
- hedis
- html-conduit < 1.3
- http-conduit
- http-types
- load-env
- postgresql-simple
- random
- regex-posix
- rio
- servant-server
- system-filepath
- text
- th-printf
- time
- transformers
- unordered-containers
- vector
- wai
- xml-conduit < 1.8

# The library contains all of our application code. The executable
# defined below is just a thin wrapper.
library:
  source-dirs: src
  default-extensions:
  - DeriveGeneric
  - FlexibleInstances
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - QuasiQuotes
  - RecordWildCards
  - TemplateHaskell
  - TypeFamilies
  ghc-options:
  - -Wall
  - -fwarn-tabs

# Runnable executable for our application
executables:
  fetch:
    main: fetch.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ted2srt

  server:
    main: server.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ted2srt
    - warp
    - wai-extra

# Test suite
tests:
  test:
    main: Main.hs
    source-dirs: test
    default-extensions:
    - NoImplicitPrelude
    - OverloadedStrings
    ghc-options: -Wall
    dependencies:
    - ted2srt
    - hspec >=2.0.0
    - process
